---
# tasks file for linux

- name: install ansible
  package:
    name: ansible
    state: present

- name: install vim
  package:
    name: vim
    state: present

- name: install net-tools
  package:
    name: net-tools
    state: present

- name: install tcptraceroute
  package:
    name: tcptraceroute
    state: present

- name: install telnet
  package:
    name: telnet
    state: present

- name: install wget
  package:
    name: wget
    state: present

- name: install tmux
  package:
    name: tmux
    state: present

- name: install python-pip
  package:
    name: python-pip
    state: present
