---
- name: Install Java via Homebrew
  homebrew_cask: name=caskroom/versions/java8
- name: Install Python3 via Homebrew
  homebrew_cask: name=python3
- name: Install AWS Cli via pip
  pip: 
    name: awscli
    state: latest
    extra_args: --upgrade --user
- name: Install pika (used by RabbitMQ)
  pip:
    name: pika
- name: Install Terraform via Homebrew
  homebrew_cask: name=terraform
- name: Install Java JDK via Homebrew
  homebrew_cask: name=java-jdk-javadoc
- name: Install Google Chrome via Homebrew
  homebrew_cask: name=google-chrome
- name: Install Git via Homebrew
  homebrew: name=git
- name: Install Docker via Homebrew
  homebrew: name=docker
- name: Install Mesos via Homebrew
  homebrew: name=mesos 
- name: Install Vault via Homebrew
  homebrew: name=vault 

